apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- package-install.yml


secretGenerator:
- name: contour-packages-values
  namespace: infra-packages
  files:
  - ../../base/contour/values.yml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: contour-packages